[package]
name = "aaronia-rtsa-sys"
version = "0.0.1"
edition = "2021"
build = "build.rs"
links = "AaroniaRTSAAPI"
license = "Apache-2.0"
description = "Bindgen wrappers for Aaronia RTSA SDK"

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.63"
